name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - hydra-core=1.3.2
  - matplotlib=3.10.6
  - pandas=2.2.3  #latest version with python 3.13 support
  - pip=24.3.1
  - scikit-learn=1.5.2  #latest version with python 3.13 support
  - jupyterlab=4.4.7
  - seaborn=0.13.2  # For statistical visualizations
  - scipy=1.14.1  # For statistical functions
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
