name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - requests=2.28.0
  - scikit-learn=1.5.2
  - pip=24.3.1
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
