name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.2.3  # Latest version with python 3.13 support
  - pytest=8.3.3  # Latest version with python 3.13 support
  - scipy=1.14.1  # Latest version with python 3.13 support
  - pip=24.3.1
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
