name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pyyaml=6.0.2
  - hydra-core=1.3.2
  - pandas=2.2.3
  - pip=24.3.1
  - pyarrow
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3