name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=24.3.1
  - requests=2.28.0
  - scikit-learn=1.5.2
  - pandas=2.2.3
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
      - -e ../wandb_utils
