name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.0
  - pip=24.3.1
  - requests=2.28.0
  - pyarrow
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
      - -e ../../components
